### ISSUE TITLE
basic_head_api usage

### ISSUE THREAD

**Issue by linas** [hansonrobotics/robots_config#3]
This is really low priority, but I want to write it down so its not forgotten:  robot.launch does `<node name="basic_head_api" pkg="basic_head_api" type="head_ctrl.py"   output="screen"/>` but basic_head_api is marked as 'for bringup only, deprecated'. What does  this file do, why is it needed, and maybe it should find a better home somewhere else?

**Comment by vytasrgl** [comment]
Currently basic head API managing simple expressions, that can be defined in webui.
